POST http://localhost:1212/send-verify HTTP/1.1
Content-Type: application/json

{
    "email": "datdo27122003@gmail.com"
}
###

POST http://localhost:1212/login HTTP/1.1
Content-Type: application/json

{
    "email": "datdo27212003@gmail.com",
    "password": "emchua18"
}
###
POST http://localhost:1212/test HTTP/1.1
